-- Mouse-code ordering (P0.2; rewritten by R11 2026-09-05).
--
-- R9's length-first expression index is RETIRED. It existed only because issue
-- order had to be recovered from the code text itself: codes are variable
-- length with a ZZZ->AAAA rollover, and a plain lexicographic sort puts 'ZZZ'
-- AFTER 'AAAA', so ordering had to go by (length, text).
--
-- mouse_ids.seq now stores the bijective base-26 ordinal directly, so issue
-- order is a plain ORDER BY seq and mouse_ids_seq_key (0002) already serves it.
-- No extra index is needed here.
--
-- Scope note kept from R9: the mouse-list query sorts mice by code columns
-- ACROSS A JOIN, so no index removes that sort. Cardinality is low (hundreds of
-- codes, thousands of mice), so an in-memory sort is fine for P0. Do not
-- over-engineer it.
--
-- This file is intentionally left without DDL rather than deleted: the
-- migration is already recorded in schema_migrations, and renumbering applied
-- migrations is what the runner's checksum guard exists to prevent.
SELECT 1;
