-- Promote task model from versioned-append `tasks` table to two-table CASE model.
--
-- CHANGES IN THIS FILE:
--   1. Retire `tasks` table (and its dependent objects, sequence, indexes).
--   2. Drop `task_status` enum (its only user was `tasks`).
--   3. Create fresh `task_status` enum with the new 5-value lifecycle.
--   4. Create `cases` table — stable identity row per case (NOT versioned).
--   5. Create `task_events` table — append-only transition log (immutable).
--
-- RETIREMENT STYLE: matches 0010 (DROP) and 0016 (DROP). `tasks` has no
-- production data; the versioned-append design is superseded by the two-table
-- model. 0005 and 0008 stay byte-identical on disk (runner's missing-file guard
-- aborts if a recorded migration disappears), but are now inert.
--
-- SIGNAL: no `task_signal` enum exists in the DB schema. `cell_signal` was
-- retired in 2026-09-05 (see 0001 comment: "promoted to the `signals` TABLE").
-- `cases` uses `signal_id BIGINT REFERENCES signals(id)`, mirroring `notes`.
--
-- SUBJECT FK for mate cycles: `mates` is versioned-append; naming a CYCLE
-- requires the origin row. The composite FK form used by `litters_mate_is_origin_fkey`
-- (FOREIGN KEY (col, col) REFERENCES mates(id, origin_mate_id)) is used here,
-- backed by the existing `mates_id_origin_key` unique constraint. A plain
-- REFERENCES mates(id) would accept mid-history version rows — wrong for a case
-- whose subject is a mate cycle.
--
-- GEN_KEY UNIQUENESS AND CANCELLATION: a cancelled case is NOT regenerated by
-- the daily batch — cancellation means "answered / intentionally closed".
-- gen_key uniqueness must therefore remain effective for cancelled-but-not-deleted
-- cases. The partial index `WHERE deleted_at IS NULL` achieves exactly this:
-- cancelled rows keep deleted_at NULL so their gen_key stays in the unique set.
-- Only a hard soft-delete (deleted_at set) frees a gen_key for reuse.
--
-- SUBJECT_KIND CHECK: mirrors the Q31 lesson from 0005. The old tasks table
-- deliberately left subject columns unconstrained because "room-level" tasks
-- (no subject) invalidated a >= 1 rule, and a mouse-AND-cage row invalidated
-- the exclusive-arc rule. The new model introduces subject_kind as the explicit
-- discriminant, which lets us state exactly what FKs are expected per kind
-- WITHOUT rejecting room-level rows. 'room' → all four subject FKs NULL is
-- now a named, valid state rather than an accident.
--
-- OPEN QUESTION (not resolved here — requires owner decision):
--   * created_by for auto-generated cases: `cases.created_by` is BIGINT NOT NULL
--     REFERENCES users(id), mirroring `litters.created_by`. Auto-generation
--     (daily batch / ETL) needs a system/service user row in `users`. No such
--     row exists; `users` CHECK allows only role IN ('admin','professor','staff').
--     A system account would need role='admin' or a new role value. The column
--     is NOT NULL here — the batch MUST supply a valid user_id. Seed a system
--     user or relax the constraint before enabling auto-generation. Flagged as
--     open question Q-SYS-USER.
--
--   * `direction` JSONB and `assigned_to` from old `tasks` (0008) are absent
--     from `cases` per the task spec. A case about moving a mouse has no column
--     for the target cage. Flag for architect review before the service layer
--     is built.

-- ---------------------------------------------------------------------------
-- 1. Retire tasks (reverse dependency order: indexes, then table, sequence
--    owned by the table drops with it; ALTER TABLE from 0008 drops with table)
-- ---------------------------------------------------------------------------
DROP TABLE tasks;
-- tasks_id_seq was OWNED BY tasks.id — it is already dropped with the table.

-- ---------------------------------------------------------------------------
-- 2. Drop old task_status enum (no remaining column references it)
-- ---------------------------------------------------------------------------
DROP TYPE task_status;

-- ---------------------------------------------------------------------------
-- 3. Fresh lifecycle enum with 5 values
-- ---------------------------------------------------------------------------
-- todo     — created, not yet started (replaces 'open')
-- doing    — actively in progress
-- done     — actor reports complete; pending professor review
-- verified — professor confirmed
-- cancelled — intentionally closed; gen_key stays in the unique set (see above)
CREATE TYPE task_status AS ENUM ('todo', 'doing', 'done', 'verified', 'cancelled');

-- ---------------------------------------------------------------------------
-- 4. cases — stable identity row (one per case, NOT versioned)
-- ---------------------------------------------------------------------------
-- current_status is a DENORMALIZED CACHE of the latest task_events row.
-- Source of truth is always task_events. The cache exists so a single-table
-- query can filter/sort without aggregating over task_events on every page load.
--
-- gen_key: NULL for manually created cases. Non-null for auto-generated cases
-- (daily batch, ETL). The partial unique index enforces idempotency: two
-- identical auto-gen triggers in the same day produce the same gen_key and
-- the second INSERT is rejected (or handled as an upsert by the caller).
-- Partial on deleted_at IS NULL — see GEN_KEY UNIQUENESS note above.
CREATE TABLE cases (
    id               BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    -- What kind of work this is, e.g. 'genotype', 'plug_check', 'wean'.
    case_type        TEXT        NOT NULL,
    -- Signal/priority from the signals table (replaces the retired task_signal
    -- enum). Mirrors notes.signal_id — signal is data, not schema.
    signal_id        BIGINT      NOT NULL REFERENCES signals (id),
    -- ---------------------------------------------------------------------------
    -- SUBJECT DISCRIMINANT
    -- Exactly what FKs are set depends on subject_kind:
    --   'mouse'  → subject_mouse_id NOT NULL, rest NULL
    --   'cage'   → subject_cage_id  NOT NULL, rest NULL
    --   'litter' → litter_id        NOT NULL, rest NULL
    --   'mate'   → subject_mate_id  NOT NULL, rest NULL (see FK note above)
    --   'room'   → all four NULL (room-level work, no specific entity)
    -- The CHECK below enforces this. This resolves the Q31 "deliberately
    -- unconstrained" decision from 0005: subject_kind names the discriminant,
    -- so each branch is now explicit rather than implicitly allowed by omission.
    -- ---------------------------------------------------------------------------
    subject_kind     TEXT        NOT NULL
        CHECK (subject_kind IN ('mouse', 'cage', 'litter', 'mate', 'room')),
    subject_mouse_id BIGINT REFERENCES mouse_meta (id),
    subject_cage_id  BIGINT REFERENCES cages (id),
    litter_id        BIGINT REFERENCES litters (id),
    -- Composite FK: names a CYCLE (origin row), not a version row. Enforced via
    -- the existing mates_id_origin_key unique constraint (id, origin_mate_id).
    -- MATCH SIMPLE: check skipped when subject_mate_id IS NULL (all non-mate kinds).
    subject_mate_id  BIGINT,
    CONSTRAINT cases_subject_mate_is_origin_fkey
        FOREIGN KEY (subject_mate_id, subject_mate_id)
        REFERENCES mates (id, origin_mate_id),
    -- CHECK: each subject_kind allows exactly its own FK(s) and requires the
    -- rest NULL.
    CONSTRAINT cases_subject_matches_kind CHECK (
        CASE subject_kind
            WHEN 'mouse'  THEN subject_mouse_id IS NOT NULL
                               AND subject_cage_id  IS NULL
                               AND litter_id        IS NULL
                               AND subject_mate_id  IS NULL
            WHEN 'cage'   THEN subject_cage_id  IS NOT NULL
                               AND subject_mouse_id IS NULL
                               AND litter_id        IS NULL
                               AND subject_mate_id  IS NULL
            WHEN 'litter' THEN litter_id        IS NOT NULL
                               AND subject_mouse_id IS NULL
                               AND subject_cage_id  IS NULL
                               AND subject_mate_id  IS NULL
            WHEN 'mate'   THEN subject_mate_id  IS NOT NULL
                               AND subject_mouse_id IS NULL
                               AND subject_cage_id  IS NULL
                               AND litter_id        IS NULL
            WHEN 'room'   THEN subject_mouse_id IS NULL
                               AND subject_cage_id  IS NULL
                               AND litter_id        IS NULL
                               AND subject_mate_id  IS NULL
        END
    ),
    -- Idempotency key for auto-generated cases. NULL = manually created.
    -- See GEN_KEY UNIQUENESS note above re: cancellation semantics.
    gen_key          TEXT,
    -- Denormalized status cache (source of truth is task_events).
    current_status   task_status NOT NULL DEFAULT 'todo',
    due_date         DATE,
    -- Who created this case and in what role at creation time.
    -- OPEN QUESTION Q-SYS-USER: auto-generated cases need a system user row.
    created_by       BIGINT      NOT NULL REFERENCES users (id),
    actor_role       TEXT        NOT NULL
        CHECK (actor_role IN ('admin', 'professor', 'staff')),
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at       TIMESTAMPTZ
);

CREATE TRIGGER cases_set_updated_at
    BEFORE UPDATE ON cases
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Idempotency: one live gen_key per case type+subject combination.
-- Cancelled cases remain in the set (deleted_at IS NULL), so a cancelled
-- plug_check for mate cycle #5 blocks a new one — cancellation = answered.
CREATE UNIQUE INDEX cases_gen_key_key
    ON cases (gen_key)
    WHERE gen_key IS NOT NULL AND deleted_at IS NULL;

-- Open/doing cases by due date — the "upcoming work" view.
CREATE INDEX cases_upcoming_idx
    ON cases (current_status, due_date)
    WHERE current_status IN ('todo', 'doing') AND deleted_at IS NULL;

-- Per-subject lookups (cage grid, mouse detail, mate timeline).
CREATE INDEX cases_subject_mouse_idx
    ON cases (subject_mouse_id)
    WHERE subject_mouse_id IS NOT NULL AND deleted_at IS NULL;

CREATE INDEX cases_subject_cage_idx
    ON cases (subject_cage_id)
    WHERE subject_cage_id IS NOT NULL AND deleted_at IS NULL;

CREATE INDEX cases_subject_mate_idx
    ON cases (subject_mate_id)
    WHERE subject_mate_id IS NOT NULL AND deleted_at IS NULL;

-- ---------------------------------------------------------------------------
-- 5. task_events — append-only transition log (immutable, mirrors 0019)
-- ---------------------------------------------------------------------------
-- One row per status transition or actor action on a case. The status column
-- records the state the case MOVED TO (not from — the prior state is the
-- previous row's status). actor_role is denormalized at event time so a later
-- role change on the user does not rewrite authorisation history.
--
-- IMMUTABILITY: same mechanism as 0019 (audit_logs). No updated_at / deleted_at
-- columns — this is a §22.4-sanctioned exception to the soft-delete rule.
-- The table grows ONLY via INSERT. REVOKE UPDATE, DELETE FROM PUBLIC prevents
-- accidental or malicious edits from any non-owner role. The migration
-- connection (table OWNER) retains full access via ownership and is unaffected
-- by the REVOKE — do not attempt to verify immutability from the owner
-- connection (it will always succeed regardless).
CREATE TABLE task_events (
    id          BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    case_id     BIGINT      NOT NULL REFERENCES cases (id),
    -- The status this event moves the case TO. Combined with ordering by id,
    -- the last event's status is the case's current state.
    status      task_status NOT NULL,
    actor_id    BIGINT      NOT NULL REFERENCES users (id),
    actor_role  TEXT        NOT NULL
        CHECK (actor_role IN ('admin', 'professor', 'staff')),
    note        TEXT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Timeline for a case's events — the canonical history read.
CREATE INDEX task_events_case_idx
    ON task_events (case_id, id ASC);

-- Actor history — "what did person X do this week".
CREATE INDEX task_events_actor_idx
    ON task_events (actor_id, created_at DESC);

-- Prevent any UPDATE or DELETE from any role that is not the table owner.
-- See 0019 for full rationale. Table OWNER retains full access via ownership.
REVOKE UPDATE, DELETE ON task_events FROM PUBLIC;
