#!/usr/bin/env bash
# Dump the live schema to a readable markdown table reference. Generated, never
# hand-edited — regenerate after every migration change.
set -euo pipefail
DB="${1:-colony_dev}"
OUT="${2:-packages/db/SCHEMA.md}"

# WHY the banner stamps a date and a migration high-water mark: the old banner
# said only "from the live colony_dev", which stays literally true forever while
# silently ceasing to describe anything. It outlived its source once — the file
# stopped at 0027, the database was gone, and three separate readers in one
# session used that line to reason about which migrations had been applied, each
# reaching a different wrong answer. A provenance line that cannot go stale is
# worse than none. These two facts CAN be compared against `ls migrations/` and
# today's date, so a reader can see the drift instead of trusting the banner.
GEN_AT="$(date +%Y-%m-%d)"
MIG_DIR="$(dirname "$0")/../migrations"
LATEST_MIG="$(ls "$MIG_DIR" 2>/dev/null | grep -E '^[0-9]{4}_' | sort | tail -1)"
LATEST_MIG="${LATEST_MIG:-unknown}"

{
  echo "# Schema reference"
  echo
  echo "> GENERATED by \`packages/db/scripts/schema-doc.sh\` from \`$DB\` on $GEN_AT."
  echo "> Highest migration on disk at generation time: \`$LATEST_MIG\`."
  echo "> This is a SNAPSHOT, not the contract — \`packages/db/migrations/\` is."
  echo "> If the newest file in that directory is above, this file is STALE; and it"
  echo "> says nothing about which migrations were ever applied, or whether \`$DB\`"
  echo "> still exists. Do not hand-edit — rerun the script."
  echo "> Diagrams: [ERD.core.png](./ERD.core.png) (domain only) · [ERD.png](./ERD.png) (all FKs)."
  echo
  psql -d "$DB" -t -A -F'|' -c "
    select t.relname
    from pg_class t join pg_namespace n on n.oid=t.relnamespace and n.nspname='public'
    where t.relkind='r' and t.relname <> 'schema_migrations' order by 1;" |
  while read -r tbl; do
    [ -z "$tbl" ] && continue
    echo "## \`$tbl\`"
    echo
    echo "| column | type | null | default | references |"
    echo "|---|---|---|---|---|"
    psql -d "$DB" -t -A -F'|' -c "
      select a.attname,
             format_type(a.atttypid, a.atttypmod),
             case when a.attnotnull then 'NOT NULL' else '' end,
             coalesce(left(pg_get_expr(d.adbin, d.adrelid), 40), ''),
             coalesce((select c.confrelid::regclass::text
                       from pg_constraint c
                       where c.contype='f' and c.conrelid=a.attrelid
                         and a.attnum = any(c.conkey)
                       limit 1), '')
      from pg_attribute a
      left join pg_attrdef d on d.adrelid=a.attrelid and d.adnum=a.attnum
      where a.attrelid = '$tbl'::regclass and a.attnum>0 and not a.attisdropped
      order by a.attnum;" |
      awk -F'|' '{printf "| `%s` | %s | %s | %s | %s |\n", $1,$2,$3,($4==""?"":"`"$4"`"),($5==""?"":"→ `"$5"`")}'
    echo
    idx=$(psql -d "$DB" -t -A -c "select indexdef from pg_indexes where tablename='$tbl' order by indexname;")
    if [ -n "$idx" ]; then
      echo '```sql'
      echo "$idx"
      echo '```'
      echo
    fi
  done
} > "$OUT"
echo "wrote $OUT ($(wc -l < "$OUT") lines)"
